### ISSUE TITLE
Text font shader - wrong glyph render

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_viewer#101]
The font is rendered by placing each character to a square, but characters have different dimensions.
I am referring to tagobject.py:
https://github.com/compas-dev/compas_viewer/blob/main/src/compas_viewer/scene/tagobject.py

These are the current issues of tagobject:
- spacing
- letters that goes below such as "q"

![image](https://github.com/compas-dev/compas_viewer/assets/18013985/290638b1-29bd-4db6-a6aa-2ade9f18f171)

If you can support another dependency e.g. Freetype which is often used for text rendering, then this is a possible tutorial:
https://github.com/Rabbid76/graphics-snippets/blob/master/example/python/text_freetype/freetype_text.md
![image](https://github.com/compas-dev/compas_viewer/assets/18013985/7e1f8c13-3023-4d13-8ac8-448d59d4ee72)

**Comment by Licini** [comment]
freetype is already a dependency, guess we are not using it properly ... checking now how to make this right
