### ISSUE TITLE
viewer is compatible with python >=3.9, python 3.8.16 wont run

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_viewer#119]
I have a following environment:
`conda create -n my_env python==3.8.16 pypy=7.3.11`

compas_viewer cannot be installed due to pyside6=6.6.1 or any version of it.
It is due to PyPy. I guess the only way to use compas_viewer is without pypy.

I am wondering if there could be any workaround?

**Comment by petrasvestartas** [comment]
It seems PySide6 is not compatible with PyPy, i think the only possibility to run viewer in such configuration is to install this package into another environment.

**Comment by petrasvestartas** [comment]
# Update

I created a new environment with 3.8.16 python. PySide6 is installed correctly.
The viewer wont run because it is compatible with python 3.9 due to typing which has a little bit different syntax in 3.8. Like tuple in 3.8 is lowecase and 3.9 is uppercase and so on.

**Comment by tomvanmele** [comment]
3.8 has reached end of life last year. it is no longer officially supported. will be difficult to add it anywhere properly...

**Comment by petrasvestartas** [comment]
@tomvanmele thanks:)
