### ISSUE TITLE
Components Structure

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas_viewer#134]
I think I agree to Tom that the component manager could be a bit of overkill right now. There is for me now a confusion between all these terms presented in our code: "manager", "factory", "component", "widget". This spawns too many layers of concepts that users have to understand when they simply want to add a button to the toolbar.

For example this line:

https://github.com/compas-dev/compas_viewer/blob/9ea5ca2d965ae17a5262700eb99c7fd95ee6897a/src/compas_viewer/ui/toolbar.py#L18

IMO really needs to be like this:
```python
self.add(Button("xxx.svg", "name",  action))
```

And when user want to customise, it should be like this:
```python
viewer.ui.toolbar.add(Button("xxx.svg", "name",  action))
```

Another issue I found that bugs me, is how the forms are currently defined:
https://github.com/compas-dev/compas_viewer/blob/9ea5ca2d965ae17a5262700eb99c7fd95ee6897a/src/compas_viewer/layout/treeform.py#L11

I think it will be better in this case the `TreeForm` does not inherent `QTreeWidget`, but have a `QTreeWidget` as its attribute. Then we can do same pattern like everywhere else using `__init__` + `lazy_init`, where `__init__` reads in configs, and `lazy_init` setup the widget. I don't see much point of having an additional layer of `TreeformComponents`. TreeForm should be able to added directly to a place like sidebar in simple API like:
```
viewer.ui.sidebar.add(Treeform(tree))
```

**Comment by PingHsunTsai** [comment]
great POV from user! I will start it soon
