### ISSUE TITLE
GUI framework

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas_viewer#4]
@tomvanmele Just to keep you in the loop. Today @ZacZhangzhuo and I had a discussion about the other potential GUI frameworks we can use in comparison of QT. [Tkinter](https://docs.python.org/3/library/tkinter.html) seems to be a very interesting candidate. Have you come across it before?

It is directly built-in with standard Python, has very simple APIs and can do perhaps 90% of what we do in view2 with QT, including things like tree form. We are now looking at if it has capacity to do something more custom like changing color of table cells, event listening and insertion of custom components. If that is all possible, for me it is a big Yes to switch.  Something definitely worth to check out.

**Comment by tomvanmele** [comment]
closing as decision has been made...
