### ISSUE TITLE
Right mouse button to pan (without shift) in 2D views

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas_viewer#71]
what you think?

**Comment by ZacZhangzhuo** [comment]
Users can always modify their key/mouse preferences in the configuration file. in including `pan`. Yet, making 2D views' keys/mouse different from 3D view would add some other code and user confusion..?

**Comment by tomvanmele** [comment]
@Licini is this now solved? can we close?

**Comment by Licini** [comment]
> @Licini is this now solved? can we close?

@tomvanmele  nop... was more of a discussion. I would personally prefer hold `left` mouse to rotate, `right` to pan, `left + shit` to multi select, over current setup of holding `left` to multi-select, `right` to rotate, and then `right + shit` to pan. How about you??

**Comment by Licini** [comment]
@PingHsunTsai what you think?

**Comment by PingHsunTsai** [comment]
@Licini  "personally" I prefer original setup in 3D, cuz is the same setting in rhino, but intern of 2D view I agree with you. It should be just right mouse click
