### ISSUE TITLE
Polyline color is set by pointscolor

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_viewer#89]
**Describe the bug**

If I am not mistaken, but when adding polyline with color, it is colorized by **pointscolor**, not **linescolor** (latest pull).

**To Reproduce**

```python
from compas_viewer import Viewer
from compas.geometry import Polyline
from compas.colors import Color
viewer = Viewer(viewmode="top")
polyline = Polyline([[0,0,0], [10,0,0], [10,10,0], [0,10,0], [0,0,0]])
viewer.add(polyline, lineswidth=5, pointscolor=Color.from_rgb255(255, 0, 0))
viewer.show()
```

**Expected behavior**

Expected to use `linescolor `attribute instead of `pointscolor`.

**Screenshots**

**Comment by ZacZhangzhuo** [comment]
Thanks for the issue!

we decided to do so:
all geometry objects are controlled by `pointcolor`, `linecolor`, `surfacecolor`, while mesh objects are controlled by `vertexcolor`,`edgecolor`, `facecolor` which is exactly how `compas.scene` behaves.

if you want to control the line colors of the polyline object, which is a geometry object, your code should be:
```python
from compas_viewer import Viewer
from compas.geometry import Polyline
from compas.colors import Color
viewer = Viewer(viewmode="top")
polyline = Polyline([[0,0,0], [10,0,0], [10,10,0], [0,10,0], [0,0,0]])
viewer.add(polyline, lineswidth=5, linecolor=Color.from_rgb255(255, 0, 0))
viewer.show()
```

![image](https://github.com/compas-dev/compas_viewer/assets/57562250/2e269281-f4f5-4873-bb88-893d5541480a)
