### ISSUE TITLE
pyside6 version is not exist

### ISSUE THREAD

**Issue by zaczhuozhang** [compas-dev/compas_viewer#92]
> I'm trying to setup the workspace for project.
> I notice there might be an error in the [req.txt](https://github.com/compas-dev/compas_viewer/blob/main/requirements.txt#L5).
> Got an error that version is not exist.

Thanks, Tsai for the request in person. I think we can put it as an issue in public so people can refer to if they have similar questions. 

I specifically pined the `PySide6` version to `6.6.1` in this [commit](https://github.com/compas-dev/compas_viewer/commit/ee07a415329d6cdfdad13968d619eaa6c07a54da)  after noticing that later version like `6.6.2` does not really work in our viewer. Pin the PySide6 version is great since [it is updating relatively quickly](https://pypi.org/project/PySide6/#history) and it takes time for us to follow up. 

To answer your question that the version is not exist, it does not happen to my PC. when I ran `pip install PySide6==6.6.1`:
```bash
Collecting PySide6==6.6.1
  Downloading PySide6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting shiboken6==6.6.1 (from PySide6==6.6.1)
  Downloading shiboken6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting PySide6-Essentials==6.6.1 (from PySide6==6.6.1)
  Downloading PySide6_Essentials-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting PySide6-Addons==6.6.1 (from PySide6==6.6.1)
  Downloading PySide6_Addons-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (3.9 kB)
Downloading PySide6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (77 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 1.9 MB/s eta 0:00:00
Downloading PySide6_Addons-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (125.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.2/125.2 MB 14.1 MB/s eta 0:00:00
Downloading PySide6_Essentials-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (82.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.3/82.3 MB 10.8 MB/s eta 0:00:00
Downloading shiboken6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (245 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.2/245.2 kB 7.4 MB/s eta 0:00:00
Installing collected packages: shiboken6, PySide6-Essentials, PySide6-Addons, PySide6
Successfully installed PySide6-6.6.1 PySide6-Addons-6.6.1 PySide6-Essentials-6.6.1 shiboken6-6.6.1
```
you can find the version [here](https://pypi.org/project/PySide6/6.6.1/).

maybe you can share your errors?

Hope it helps.

**Comment by PingHsunTsai** [comment]
Hi @zaczhuozhang, I'm running the setting from Ubuntu20.04 and Python 3.8.10, I run into this error when launch `pip install -r requirements-dev.txt`
```
Collecting PyOpenGL-accelerate
  Using cached PyOpenGL_accelerate-3.1.7-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)
Collecting freetype-py
  Using cached freetype_py-2.4.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.0 MB)
ERROR: Could not find a version that satisfies the requirement PySide6==6.6.1 (from compas_viewer==1.0.1->-r requirements-dev.txt (line 13)) (from versions: 6.0.0a1.dev1606911628, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.2.0, 6.2.1, 6.2.2, 6.2.2.1, 6.2.3, 6.2.4)
ERROR: No matching distribution found for PySide6==6.6.1 (from compas_viewer==1.0.1->-r requirements-dev.txt (line 13))

```
**Solution**

I found a solution by [building from source here](https://pypi.org/project/PySide6/) and run the `pip install -r requirements-dev.txt` again.

Thanks for your prompt reply.
